num1 = 1000
num2 = 500

print(num1 > num2) # True COMPARA SI EL PRIMER VALOR ES MAYOR QUE EL SEGUNDO
print(num1 < num2) # False COMPARA SI EL PRIMER VALOR ES MENOR QUE EL SEGUNDO
print(num1 == num2) # False COMPARA SI EL PRIMER VALOR ES IGUAL QUE EL SEGUNDO
print(num1 != num2) # True COMPARA SI EL PRIMER VALOR ES DIFERENTE QUE EL SEGUNDO
print(num1 >= num2) # True COMPARA SI EL PRIMER VALOR ES MAYOR O IGUAL QUE EL SEGUNDO
print(num1 <= num2) # False COMPARA SI EL PRIMER VALOR ES MENOR O IGUAL QUE EL SEGUNDO

# COMPARACIONES ENTRE CADENAS

cadena1 = "Hola"
cadena2 = "Mundo"

print(cadena1 > cadena2) # False, COMPARA SI EL PRIMER VALOR ES MAYOR QUE EL SEGUNDO
print(cadena1 < cadena2) # True, COMPARA SI EL PRIMER VALOR ES MENOR QUE EL SEGUNDO
print(cadena1 == cadena2) # False, COMPARA SI EL PRIMER VALOR ES IGUAL QUE EL SEGUNDO
print(cadena1 != cadena2) # True, COMPARA SI EL PRIMER VALOR ES DIFERENTE QUE EL SEGUNDO
print(cadena1 >= cadena2) # False, COMPARA SI EL PRIMER VALOR ES MAYOR O IGUAL QUE EL SEGUNDO
print(cadena1 <= cadena2) # True, COMPARA SI EL PRIMER VALOR ES MENOR O IGUAL QUE EL SEGUNDO
